# This constitutes the default configuration file for the mpc-generator. 
#
# Reference:  Trajectory Generation for Mobile Robots in a Dynamic Environment using Nonlinear Model Predictive Control. [CASE2021]
#
# This constitutes the default configuration file for the mpc-generator. 
################################################################################

# Physical parameters and limitations of the motion model
vehicle_width:  0.5   # Vehicle width in meters
vehicle_margin: 0.25  # Vehicle extra safe margin
lin_vel_min: -0.5   # Vehicle contraint on the minimal velocity possible
lin_vel_max: 1.5    # Vehicle contraint on the maximal velocity possible
lin_acc_min: -1     # Vehicle contraint on the maximal linear retardation
lin_acc_max: 1      # Vehicle contraint on the maximal linear acceleration
ang_vel_max: 0.5    # Vehicle contraint on the maximal angular velocity
ang_acc_max: 3      # Vehicle contraint on the maximal angular acceleration (considered to be symmetric)

# Parameters specific to the solution algorithm
ts: 0.2             # Size of the time-step (sampling time)
N_hor: 20           # The length of the receding horizon controller
throttle_ratio: 0.8 # What % of the maximal velocity should we try to
num_steps_taken: 1  # How many steps should be taken from each mpc-solution. Range (1 - N_hor)
vel_red_steps: 10   # Number of timesteps for braking when close to goal position

# Weights
lin_vel_penalty: 0      # Cost for linear velocity control action
lin_acc_penalty: 10.0   # Cost for linear acceleration 
ang_vel_penalty: 0      # Cost angular velocity control action
ang_acc_penalty: 5.0    # Cost angular acceleration
qcte: 200               # Cost for cross-track-error from each line segment
qp: 0.0                 # Cost for position deviation (each time step vs reference point)
qv: 10.0                # Cost for speed deviation each time step
qtheta: 0.0             # Cost for each heading relative to the final refernce position
qpN: 0.0                # Terminal cost; error relative to final reference position         
qthetaN: 0.0            # Terminal cost; error relative to final reference heading 

# Helper variables (Generally does not have to be changed)
ns: 3     # Number of states for the robot (x,y,theta)
nq: 10    # Number of optimization parameters
nu: 2     # Number of control inputs
Nobs: 10  # Maximal number of obstacles
nobs: 3   # Number of variables per obstacles
Ndynobs: 3 # Maximal number of dynamic obstacles
ndynobs: 5 # Number of variables per dynamic obstacle

# Building options in the optimizer
build_type: 'release'           # Can have 'debug' or 'release'
build_directory: 'mpc_build'  # Name of the directory where the build is created
bad_exit_codes: ["NotConvergedIterations", "NotConvergedOutOfTime"] # Optimizer specific names
optimizer_name: 'navigation' # optimizer type